# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Googleuser',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('upload', models.ImageField(upload_to='djangowebtech/django/techioapp/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('theme', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techioapp.Googleuser')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techioapp.Party')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techioapp.Googleuser')),
            ],
        ),
    ]
