# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
