# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleuser',
            name='name',
        ),
    ]
