# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0002_remove_googleuser_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together=set([('id_user', 'id_party')]),
        ),
    ]
