# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0003_auto_20180328_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='lattitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='party',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
