# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upload',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'djangowebtech/django/techioapp/static/temp'),
        ),
    ]
