# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0004_auto_20171219_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='djangowebtech/django/techioapp/static/img'),
        ),
    ]
