# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0005_auto_20171219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(upload_to=b'djangowebtech/django/techioapp/static/img'),
        ),
    ]
