# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techioapp', '0006_auto_20171219_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(upload_to='djangowebtech/django/techioapp/static/img'),
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
